name: Python Tests

on:
  push:
    branches:
      - main  # or your default branch name
  pull_request:
    branches:
      - main  # or your default branch name

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        python setup.py install
        # install any other dependencies you have
        
    - name: Run tests
      run: pytest
