name: Unit tests

on:
  push:
    branches:
      - main
      - poetry_unit_tests
  pull_request:
    branches: 
      - main
      - poetry_unit_tests

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup poetry and pytest
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        pip install pytest
    - name: Install dependencies and run
      run: |
        poetry env use python
        poetry update
        poetry run pytest
